import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/cours.module.css";

const Cours: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-cesi.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Cours de React</a>
        </h1>

        <div>
          <h2 className={styles.h2}>
            Découvrez le monde des frameworks front-end
          </h2>

          <p>
            Vous en avez peut-être déjà entendu parler, les frameworks front-end
            sont partout. Toutes les grandes entreprises de la Tech les
            utilisent au quotidien : Facebook, Twitter, Amazon, GitLab, pour n
            en citer que quelques-unes. Ce sont également de nombreuses
            startups, dès leur création, qui se lancent sur React, Vue, et d
            autres ; ou encore les grandes entreprises qui font évoluer leur
            codebase pour se tourner vers elles. Mais avant d aller plus loin,
            qu est-ce qu un framework en code ? On appelle framework front-end
            tout ensemble de classes, fonctions et utilitaires qui nous facilite
            la création d applications web. Ces outils sont compatibles avec
            tous les navigateurs. Plus généralement, le but est d éviter de
            réinventer la roue pour n importe quel besoin classique d une
            application : gestion de l interface utilisateur, des événements, du
            DOM, des formulaires, de l’évolution dans le temps des données
            manipulées par l interface, etc. En plus, initialiser une base de
            code avec un framework simplifie non seulement votre prise de
            marques, mais aussi l’intégration d’une nouvelle personne sur la
            codebase.
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Cours;
